name: "Testing"
on: pull_request
      
jobs:
  tests:
    name: build container and execute pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --build-arg SINERGYM_EXTRAS=[DRL,test] --tag pullrequest/sinergym:latest
      - name: Execute tests from container
        run: docker run -t pullrequest/sinergym:latest /bin/bash -c 'pytest tests/ -vv'
